name: Build
on:
  push:
    branches:
      - main # the name of your main branch
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checking out
      uses: actions/checkout@main
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    - name: Build and analyze code
      run: mvn clean sonar:sonar -Dsonar.host.url=SONAR_HOST_URL -Dsonar.login=admin -Dsonar.password=Dhanu@10 
