name: Build
on:
  push:
    branches:
      - main # the name of your main branch
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checking out
      uses: actions/checkout@main
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    - name: SonarQube Scan
      run: mvn clean verify sonar:sonar -Dsonar.projectKey=Github-Action-Scan -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} -Dsonar.login=sqp_54166eb1290c2a0635b27d82386dde574e723bac
